### ISSUE TITLE
Ineffetive area Flow areas

### ISSUE THREAD

**Issue by jorgealmerio** [erpas/rgis#13]
When I try to use RAS 1D Ineffetive area Flow areas, I got:

"Finding ineffective flow areas for cross-sections
DataError('Geometry type (Point) does not match column type (LineString)\n',)
Process aborted!"

What's the Problem?

**Comment by erpas** [comment]
Can you share the data you're working on?

Radek

2015-12-10 14:18 GMT+01:00 jorgealmerio <notifications@github.com>:

> When I try to use RAS 1D Ineffetive area Flow areas, I got:
>
> "Finding ineffective flow areas for cross-sections
> DataError('Geometry type (Point) does not match column type
> (LineString)\n',)
> Process aborted!"
>
> What's the Problem?
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/erpas/rgis/issues/13>.
>



-- 
Używam wolnego oprogramowania:
https://www.gnu.org/philosophy/philosophy.pl.html

**Comment by erpas** [comment]
I would say, there is an ineffective area that touches a cross-section at exactly one point. Please make them disjoint and let me know if the problem persist.

**Comment by erpas** [comment]
Fixed for QGIS 3.
