### ISSUE TITLE
2D flow area creation

### ISSUE THREAD

**Issue by civilboy90** [erpas/rgis#14]
hi everyone,
i would like to built 2D mesh but i failed to create 2d flow area. i can create breakline layer. but for 2D flow area, it says 
Import data into RAS PostGIS tables...
Importing data from flow_area...
WARNING:
Source geometry is MULTIPART but target is SINGLEPART! Layer skipped. 
i made sure to use correct attributes, any suggession?

**Comment by erpas** [comment]
2D Flow Areas and breaklines must be a single type of geometry.
Use 'Multipart to singleparts' from QGIS Processing Toolbox on your source geometry to make sure they are single geometries.
And please let us know if that helped.

**Comment by civilboy90** [comment]
New problem emerged.
Import data into RAS PostGIS tables...
Importing data from Single parts...
InternalError('geometry requires more points\nHINT:  "...7, 568725 4137186.35713820718228817))" <-- parse error at position 112 within geometry\n',)
OK
Importing data from breaklines...
OK
  Imported layers:
    2D Flow Areas
    2D Area Breaklines

**Comment by erpas** [comment]
Look into the attribute table of 2d Flow Area source layer. Check how many objects is there and compare it with your expectations. I suppose you have a polygon with only 2 points. If that is the case, delete it and run import once again.

If the problem persist, consider sharing the geometry (shapefile) - that would be much easier for us to find the real problem.

**Comment by civilboy90** [comment]
that is my source geometry file for the 2D flow area
https://drive.google.com/file/d/0B8Pfh3ZR4kikNmlnYlRSVE9NTkE/view?usp=sharing
i could't upload here.

**Comment by erpas** [comment]
The 2D area geometry must be a single polygon - not a mesh of polygons:

![your_mesh](https://cloud.githubusercontent.com/assets/3106699/11899730/6590c354-a5a1-11e5-96d8-4ae19d6b43a8.png)

It should look like this:

![mesh_ok](https://cloud.githubusercontent.com/assets/3106699/11899797/f2d77672-a5a1-11e5-95ce-08b7b1ad6b82.png)

Here is the single geometry you can use with RiverGIS: [2darea.zip](https://github.com/erpas/rgis/files/66752/2darea.zip)
Please, note that there is no projection defined for the layer. Be sure to define it before importing the layer into river database.

Good luck!

**Comment by civilboy90** [comment]
I am doing master and my thesis is about making dam break analysis with 2D hydraulic analysis. i have been working for so long but am yet to achieve a good result. the simulations i ve made reveals an illogical, unreasonable water movements. although i took help from the ras solution website and professionals working there, i could not fix. With last hope, i saw your post there and now i am working on it to get my mesh right. Maybe it would help. Could you please check my results made solely on HECRAS?
https://drive.google.com/file/d/0B8Pfh3ZR4kikOFBKeUJmcHFwcWs/view?usp=sharing

Also i am curious how you could be able to leave the perimeter of the 2D flow area alone. i could not remove objects inside of the poligon for that shapefile layer.

I have created computational points and then mesh preview after defining the projection for the source files. The process was completed and layers were created. But meshes are not seen in canvas.

**Comment by erpas** [comment]
I hope you got it solved. Closing the issue.
