### ISSUE TITLE
HEC RAS SDF file import

### ISSUE THREAD

**Issue by marjanmo** [erpas/rgis#15]
Am I missing something or is it not possible to import the sdf export file in riverigs?

**Comment by erpas** [comment]
Currently loading the HEC-RAS Export SDF into RiverGIS is NOT possible.
If you want to use your previous model geometry, use the Mapper to export the geometry parts as shapefiles and load them to QGIS.
Hope this helps,

Radek Pasiok

**Comment by marjanmo** [comment]
Thanks, you're the champ! All the props for developing this plugin!

Marjan Moderc
