### ISSUE TITLE
BUG: Searching raters in the TOC

### ISSUE THREAD

**Issue by vicente-medina** [erpas/rgis#26]
If there is a raster layer in the TOC using UTF-8 special characters (i.e: "Mapa topogr**à**fic de Catalunya 1:1.000.000") the plugin fails trying to set the topographic raster. It searches all the available raster layers in the TOC to fill the combo box of the settings form, in case of finding names with special characters in fails.

**Comment by erpas** [comment]
For RiverGIS versions < 3, please, rename the problematic raster to include only ASCII characters.

There should be no problem for RiverGIS 3.
