### ISSUE TITLE
2D mesh geometry import issue for large meshes

### ISSUE THREAD

**Issue by mdweber2** [erpas/rgis#28]
I've been successfully using RiverGIS for mesh creation, but if a mesh includes too many cells the HEC-RAS Geometry import fails. I'm not sure where the threshold is, but it definitely does not work at around 250,000 cells. This is a problem for me, as I often work with large 2D models. 

What happens is that the cells that were created along the breaklines are absent. Here's an example screenshot where the regular grid imported, but the curvilinear portion within the channel fails. 

![image](https://cloud.githubusercontent.com/assets/20648129/25248461/3796ee1c-25c3-11e7-9605-442d49e81532.png)

Anyone else notice this issue? What is going on here?

Thanks,
-Matt

**Comment by erpas** [comment]
Hi Matt,

Thanks for your report. We didn't get into such problems. Would you like to share your dataset? That would help us reproduce the problem and look into it if we had the following layers:

1. FlowAreas2D
2. BreakLines2D
3. BreakPoints2D (if any)
4. DTM (optional)

**Comment by mdweber2** [comment]
Here's an example dataset that did not work. These are the shapefiles that I used to load into the FlowAreas2D and BreakLines2D files.

[QGIS_Files.zip](https://github.com/erpas/rgis/files/945449/QGIS_Files.zip)

Thanks,
-Matt

**Comment by erpas** [comment]
Thanks Matt!
The size of your model might not be relevant here. The problem is that your breakline endpoints are located outside of the 2d flow area. Modify your breakline to start and end inside of the 2d area - it should not cross the 2d area boundary. Hope that helps.
I have created a new issue for that ( #29 ) - we will add a check for breaklines laying in 2d flow area exterior.

**Comment by mdweber2** [comment]
I'm not positive that that is what is going on here. Here's an example where my breakline extends beyond the boundary polygon and the RAS Geometry import works just fine. One difference, is that this dataset only generates ~50,000 cells whereas my previous example generates over 250,000 cells, leading me to believe its a size issue. I'll try modifying the breaklines for the original example and see if I can get the mesh to import correctly. 

Here's the other example dataset:

[LAR_RiverGIS_example.zip](https://github.com/erpas/rgis/files/952665/LAR_RiverGIS_example.zip)

Thank you for you quick reply!
-Matt
