### ISSUE TITLE
Error while opening "Options" or "Elevations"

### ISSUE THREAD

**Issue by Emeldeka** [erpas/rgis#50]
Hello,

I receive a Python Error message when I try to open "Options" (in order to assign the DTM file) the window Options doesn't even open itself. And I receive the same message opening   XS Cut Lines Attributes/Elevations.

_Traceback (most recent call last):
			  File "C:/Users/emeldeka/.qgis2/python/plugins\rivergis\rivergis.py", line 344, in options
			    dlg = DlgSettings(self, widget=widget)
			  File "C:/Users/emeldeka/.qgis2/python/plugins\rivergis\dlg_settings.py", line 58, in __init__
			    item = QStandardItem('{0}'.format(layer.name())) #layerId
			UnicodeEncodeError: 'ascii' codec can't encode character u'\xe9' in position 32: ordinal not in range(128)_

What can I do ? 
I have been trying whith other version of QGIS and it is the same issue.

Thank you for your help and advice.

Emeldeka

**Comment by erpas** [comment]
Try to remove any non-ASCII chars from layers names.
